// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PromomashTestApp.Infrastructure;

#nullable disable

namespace PromomashTestApp.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20221008073733_Init")]
    partial class Init
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "6.0.9");

            modelBuilder.Entity("PromomashTestApp.Infrastructure.Entities.Country", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.ToTable("countries");

                    b.HasData(
                        new
                        {
                            Id = new Guid("250c8522-ee4d-42fa-ba06-97dc33f7f3af"),
                            Name = "Country 1"
                        },
                        new
                        {
                            Id = new Guid("ef82605c-046c-403e-a7ec-f40d799f64f7"),
                            Name = "Country 2"
                        });
                });

            modelBuilder.Entity("PromomashTestApp.Infrastructure.Entities.Province", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<Guid>("CountryId")
                        .HasColumnType("TEXT")
                        .HasColumnName("country_id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.HasIndex("CountryId");

                    b.ToTable("provinces");

                    b.HasData(
                        new
                        {
                            Id = new Guid("09d8c1cf-9f0d-4c66-9d8b-109767076015"),
                            CountryId = new Guid("250c8522-ee4d-42fa-ba06-97dc33f7f3af"),
                            Name = "Provice 1.1"
                        },
                        new
                        {
                            Id = new Guid("f67558e4-3103-4e2e-ad25-91f2f666edb0"),
                            CountryId = new Guid("250c8522-ee4d-42fa-ba06-97dc33f7f3af"),
                            Name = "Provice 1.2"
                        },
                        new
                        {
                            Id = new Guid("a35f5eb1-6782-4f47-9ef8-f004fcbe2269"),
                            CountryId = new Guid("ef82605c-046c-403e-a7ec-f40d799f64f7"),
                            Name = "Provice 2.1"
                        },
                        new
                        {
                            Id = new Guid("99f881e9-4207-47cb-8960-edd2361ce212"),
                            CountryId = new Guid("ef82605c-046c-403e-a7ec-f40d799f64f7"),
                            Name = "Provice 2.2"
                        });
                });

            modelBuilder.Entity("PromomashTestApp.Infrastructure.Entities.Province", b =>
                {
                    b.HasOne("PromomashTestApp.Infrastructure.Entities.Country", "Country")
                        .WithMany()
                        .HasForeignKey("CountryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Country");
                });
#pragma warning restore 612, 618
        }
    }
}
